# Generated by Django 3.2.9 on 2021-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='100.00', max_length=10),
        ),
    ]
