# Generated by Django 3.2.9 on 2021-12-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_alter_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='statement',
            field=models.TextField(null=True),
        ),
    ]
