# Generated by Django 3.2.9 on 2021-12-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20211214_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.CharField(default='-', max_length=128),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title_id',
            field=models.CharField(max_length=64),
        ),
    ]
