# Generated by Django 4.0.1 on 2022-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_problem_can_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContestLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
    ]
