# Generated by Django 4.0.1 on 2022-04-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='sub_contest_list',
        ),
        migrations.DeleteModel(
            name='SubContest',
        ),
    ]
