# Generated by Django 4.0.1 on 2022-04-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_remove_contest_sub_contest_list_delete_subcontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.contest')),
                ('problem_list', models.ManyToManyField(to='problem.Problem')),
                ('sub_contest_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.subcontestlevel')),
            ],
        ),
    ]
